version: 2.1

workflows:
  django-web-app: 
    jobs:
      - build-and-test
          context:
            - python

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
